server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/mybatis?allowMultiQueries=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: min
    password: wjdqhqhdks
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

mybatis:
  configuration:
    return-instance-for-empty-row: true
  mapper-locations: classpath:mapper/**.xml
  type-aliases:package: com.minBoard.vo, com.minBoard.paging, com.minBoard.dto

custom:
  path:
    uploadPath: 'D:/board/file/'      # 게시판 파일 업로드 경로